version: '3.1'

services:

  wordpress:
    image: wordpress:5.2-php7.2
    ports:
      - 8080:80
    volumes:
      - $PWD/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - 8081:80
    depends_on:
      - db

  db:
    image: mariadb:10.4-bionic
    ports:
      - 3306:3306
    volumes:
      - $PWD/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
